development:
  adapter: postgresql
  encoding: unicode
  database: cordova-rails_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: cordova-rails_production
  pool: 5
